os:
  - linux
  - osx
language: node_js
node_js:
  - '14'
  - '13'
  - '12'
dist: xenial
services:
  - xvfb
before_script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install libsecret-1-dev;
  - export DISPLAY=:99.0
install:
  - npm set progress=false
  - npm install
script:
  - ng lint
  - npm run test
  - npm run e2e
  - npm run build
after_success:
  - bash <(curl -s https://codecov.io/bash)